import Head from 'next/head'
import styled from 'styled-components';
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Whatsapp 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Sidebar mobile={false} />
      <PlaceholderSvg>
          <SVG src='./WhatsAppSvg.svg' />
      </PlaceholderSvg>
    </Container>
  )
}

const Container = styled.div`
   display: flex;
`;

const PlaceholderSvg = styled.div`
    flex: 1;
    height: 100vh;
    background-color: whitesmoke;
    display: grid;
    place-items: center;
    @media (max-width: 768px) {
    display: none;
  }
`;

const SVG = styled.img`
    width: 40%;
`;